apiVersion: v1
kind: Service
metadata:
  name: {{ include "bluegreen-deployment.fullname" . }}
  labels:
    app: {{ include "bluegreen-deployment.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: {{ include "bluegreen-deployment.name" . }}
